apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "calc-chart.fullname" . }}
  labels:
    app: {{ include "calc-chart.name" . }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "calc-chart.name" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: calculator-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java", "-cp", "src:lib/*", "CalculatorApp"]
          args:
            - "{{ .Values.a }}"
            - "{{ .Values.b }}"
            - "{{ .Values.op }}"
